### ISSUE TITLE
Creating separate repos for render deploy 

### ISSUE THREAD

**Issue by PratyushaKumarKar** [PratyushaKumarKar/crowd_counting_app#1]
We need a frontend and a backend separate repo for running it on render

**Comment by Sid70** [comment]
[Awiros PPT Presentation.pptx](https://github.com/PratyushaKumarKar/crowd_counting_app/files/12903443/Awiros.PPT.Presentation.pptx)

**Comment by PratyushaKumarKar** [comment]
Issue resolved in render
